# Generated by Django 5.1 on 2025-01-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0002_products_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='prod_images/'),
        ),
    ]
