# Generated by Django 5.1 on 2025-01-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0003_remove_products_logo_company_logo_products_pro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loan_amt', models.IntegerField()),
                ('months_of_repayment', models.IntegerField()),
                ('rate_of_intrest', models.FloatField()),
            ],
        ),
    ]
