# Generated by Django 5.1.4 on 2025-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0004_emiform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_mobile', models.IntegerField()),
                ('customer_ID', models.CharField(max_length=40)),
                ('customer_driving_licence_id', models.CharField(max_length=80)),
                ('Bike_name', models.CharField(max_length=50)),
                ('bike_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EMIform',
        ),
    ]
